### ISSUE TITLE
VRScreenCap app - HMD all black 

### ISSUE THREAD

**Issue by RAGEdemon** [mbucchia/OpenXR-Vk-D3D12#1] opened 2022-07-29 22:53 UTC
Thank you for this.

[https://github.com/artumino/VRScreenCap](https://github.com/artumino/VRScreenCap)

WMR headset: HP Reverb G2

When the app is launched, HMD goes to black.

**Comment by mbucchia** [comment] 2022-07-29 23:55
Hello,

I have downloaded v0.1.0 of this application from here: https://github.com/artumino/VRScreenCap/releases/tag/0.1.0

I have tested it with:

- Oculus Quest 2
- SteamVR OpenXR runtime

Both of these OpenXR runtimes _natively_ support Vulkan (ie: can be trusted). I get black screen for both.

As far as I can tell, the issue is not with OpenXR-Vk-D3D12, since the app is giving me a black screen with 2 fully qualified OpenXR runtimes.

Please contact the developer of that application.

**Comment by artumino** [comment] 2022-07-30 09:24
A black screen when no geo11 game is running is the correct behavior.
I think you can close this one and we'll continue with the other issue for eventual other VRScreenCap bugs.

**Comment by mbucchia** [comment] 2022-07-30 15:53
Thank you @artumino. I would love to hear if it works eventually, but I'm not really sure what these geo11 games are or how to set them up.

Will close for now.

**Closed by mbucchia** 2022-07-30 15:53 UTC
